### PR TITLE
Add CORS support by adding the JSONP dataType parameter.

### LINKED ISSUE #8: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Error occurs when trying to get data from that Github Jobs API. You can watch error in dev tools console bar. Modify in withJobs branch

### PR DESCRIPTION
**Pull request by lpegoraro**
This fixes #8

### CODE REVIEW

**Comment by prokawsar** [comment]
@lpegoraro Thanks a lot for contribution. Have you tested it? It's not working, returning the same error.

**Comment by prokawsar** [comment]
Also I have tried
```react.js
getData.push(axios.get('https://jobs.github.com/positions.json?description='+this.state.search), {
         // to allow CORS in the client side
         dataType: 'json',
         headers: {"Access-Control-Allow-Origin": '*' }
  });
```

**Comment by lpegoraro** [comment]
hmm that is strange, it worked when I attempted from the console.
I tried only in the console, not in the actual implementation of the code. 
Let me see If anything is missing.

Also this header you tried, will not work, this changes things from the server side.

**Comment by lpegoraro** [comment]
That is very strange since the GitHub API shows that they support `jsonp` [here](https://jobs.github.com/api).

**Comment by lpegoraro** [comment]
Now I had time to finish it, sorry the delay though.

image


Cheers! Happy coding!

**Pull request merged**
